---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: gitea-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
  namespace: gitea-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      dnsConfig:
        nameservers: [ "192.168.1.5" ]
        searches: [ "lab" ]
      containers:
      - name: gitea
        #image: gitea/gitea:1.22.0-rc1
        image: git.lab/lab/gitea:latest
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: timezone-volume
          mountPath: /etc/timezone
        - name: localtime-volume
          mountPath: /etc/localtime
      volumes:
      - name: data-volume
        hostPath: { path: /opt/state/gitea_svc/data }
      - name: timezone-volume
        hostPath: { path: /etc/timezone }
      - name: localtime-volume
        hostPath: { path: /etc/localtime }
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
# Port used by caddy-router-deployment
apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: gitea-ns
spec:
  selector:
    app: gitea
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 1180
    targetPort: 3000

---
# Handled by ServiceLB (i.e. Klipper) in K3s
apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh-service
  namespace: gitea-ns
spec:
  selector:
    app: gitea
  type: LoadBalancer
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
