---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-secrets
  namespace: lan-lab-ldap-ns
type: Opaque
data:
  LDAP_ADMIN_USERNAME: YWRtaW4= # b64(admin) DN: cn=admin,dc=lab,dc=lan
  LDAP_ADMIN_PASSWORD: cGFzc3dvcmQ= # b64(password)
  LDAP_CONFIG_ADMIN_USERNAME: Y29uZmln # b64(config) DN: cn=config,cn=config
  LDAP_CONFIG_ADMIN_PASSWORD: cGFzc3dvcmQ= # b64(password)
  LDAP_USERS: dXNlcg== # b64(user)
  LDAP_PASSWORDS: cGFzc3dvcmQ= # b64(password)
