---
# Handled by ServiceLB (i.e. Klipper) in K3s
apiVersion: v1
kind: Service
metadata:
  name: ldapadmin-service
  namespace: lan-lab-ldap-ns
spec:
  selector:
    app: lan-lab-ldapadmin
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 1380
    targetPort: 80