services:
  openldap-app:
    #network_mode: host
    hostname: ldap.lab.lan
    #image: tiredofit/openldap:2.6-7.6.13
    image: tiredofit/openldap-fusiondirectory:2.6-1.4
    extra_hosts:
    - dockerhost:host-gateway
    - ldap.lab.lan:192.168.1.6
    container_name: openldap-app
    ports:
      - 389:389
      - 636:636
    volumes:
      - ./backup:/data/backup
      - ./data:/var/lib/openldap
      - ./config:/etc/openldap/slapd.d
      - ./certs:/certs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=openldap-app

      - CONTAINER_ENABLE_MONITORING=TRUE

      - FUSIONDIRECTORY_ADMIN_USER=fd-admin
      - FUSIONDIRECTORY_ADMIN_PASS=admin
      - ORGANIZATION=Lab

      - HOSTNAME=ldap.lab.lan
      - DOMAIN=lab.lan
      - BASE_DN=dc=lab,dc=lan

      - LOG_LEVEL=256

      - ADMIN_PASS=admin
      - CONFIG_PASS=config

      - DEBUG_MODE=FALSE

      - ENABLE_READONLY_USER=FALSE
      - READONLY_USER_USER=reader
      - READONLY_USER_PASS=reader

      - ENABLE_TLS=TRUE
      - TLS_CRT_FILENAME=cert.pem
      - TLS_KEY_FILENAME=key.pem
      - TLS_ENFORCE=FALSE
      - TLS_CIPHER_SUITE=ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:-DHE-DSS:-RSA:!aNULL:!MD5:!DSS:!SHA
      - TLS_VERIFY_CLIENT=never
      - SSL_HELPER_PREFIX=ldap

      - ENABLE_REPLICATION=FALSE
      # - REPLICATION_CONFIG_SYNCPROV=binddn="cn=config" bindmethod=simple credentials="admin" searchbase="cn=config" type=refreshAndPersist retry="5 5 60 +" timeout=1 filter="(!(objectclass=olcGlobal))"
      # - REPLICATION_DB_SYNCPROV=binddn="cn=admin,dc=lab,dc=lan" bindmethod=simple credentials="admin" searchbase="dc=lab,dc=lan" type=refreshAndPersist interval=00:00:00:10 retry="5 5 60 +" timeout=1
      # - REPLICATION_HOSTS=ldap://ldap1.example.com ldap://ldap2.example.com ldap://ldap3.example.com
      - REMOVE_CONFIG_AFTER_SETUP=false

      - ENABLE_BACKUP=TRUE
      - BACKUP_INTERVAL=0400
      - BACKUP_RETENTION=10080

      - PLUGIN_AUDIT=TRUE
      - PLUGIN_DSA=TRUE
      - PLUGIN_LDAPDUMP=TRUE
      - PLUGIN_LDAPMANAGER=TRUE
      - PLUGIN_MAIL=TRUE
      - PLUGIN_PERSONAL=TRUE
      - PLUGIN_PPOLICY=TRUE
      - PLUGIN_SSH=TRUE
      - PLUGIN_SUDO=TRUE
      - PLUGIN_WEBSERVICE=TRUE
    
    restart: always

  # ldapsearch -x -b 'dc=lab,dc=lan' -H ldap://192.168.1.6 -D 'cn=admin,dc=lab,dc=lan' -W '(objectClass=*)'

  fusiondirectory-app:
    #network_mode: host
    container_name: fusiondirectory-app
    image: tiredofit/fusiondirectory:1.4-2.8.4
    ports:
      - 80:80
    extra_hosts:
    - dockerhost:host-gateway
    - ldap.lab.lan:192.168.1.6
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.fusiondirectory-app.rule=Host(`fusiondirectory.example.com`)
    #   - traefik.http.services.fusiondirectory-app.loadbalancer.server.port=80
    volumes:
      - ./logs:/www/logs
      #- ./custom:/assets/fusiondirectory
      #- ./plugins-custom:/assets/plugins-custom
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=fusiondirectory-app

      - ENABLE_ARGONAUT=FALSE
      - PLUGIN_AUDIT=TRUE
      - PLUGIN_DSA=TRUE
      - PLUGIN_LDAPDUMP=TRUE
      - PLUGIN_LDAPMANAGER=TRUE
      - PLUGIN_MAIL=TRUE
      - PLUGIN_PERSONAL=TRUE
      - PLUGIN_PPOLICY=TRUE
      - PLUGIN_SSH=TRUE
      - PLUGIN_SUDO=TRUE
      - PLUGIN_WEBSERVICE=TRUE

      - LDAP01_HOST=ldap.lab.lan
      - LDAP01_BASE_DN=dc=lab,dc=lan
      - LDAP01_ADMIN_DN=cn=admin,dc=lab,dc=lan
      - LDAP01_ADMIN_PASS=admin
      - LDAP01_PORT=389
      - LDAP01_NAME=Production

     #- LDAP02_BASE_DN=dc=example,dc=org
     #- LDAP02_ADMIN_DN=cn=admin,dc=example,dc=org
     #- LDAP02_HOST=openldap-fusiondirectory2
     #- LDAP02_ADMIN_PASS=password2
     #- LDAP02_NAME=Development
     #- LDAP02_TLS=TRUE
    # networks:
    #   - proxy
    #   - services
    restart: always

  # ldap_svc:
  #   #image: git.lab/lab/freeipa-server-rocky-9:stage
  #   image: git.lab/lab/ldap_svc:stage
  #   container_name: ldap.lab.lan
  #   hostname: ldap.lab.lan
  #   network_mode: host
  #   build:
  #     dockerfile_inline: |
  #       #FROM tiredofit/openldap-fusiondirectory:2.6-1.4-latest
  #       #FROM tiredofit/openldap-fusiondirectory:2.6-1.4-7.6.13
  #       FROM tiredofit/openldap-fusiondirectory:2.6-1.4-7.6.5
  #     extra_hosts: [ "dockerhost:host-gateway" ]
  #   restart: unless-stopped
  #   dns: [ "9.9.9.9" ]
  #   dns_search: lab.lan
  #   extra_hosts:
  #   - dockerhost:host-gateway
  #   - ldap.lab.lan:192.168.1.6
  #   #entrypoint: ["/init"]
  #   environment:
  #   - FUSIONDIRECTORY_ADMIN_USER=admin
  #   - FUSIONDIRECTORY_ADMIN_PASS=password
  #   - ORGANIZATION=lab
  #   - DOMAIN=lab.lan
  #   - ADMIN_PASS=admin
  #   - CONFIG_PASS=config
  #   - LOG_LEVEL=256
  #   volumes:
  #   # data
  #   - ./state/openldap/data:/var/lib/openldap
  #   # config
  #   - ./state/openldap/config:/etc/openldap/slapd.d
  #   # init scripts
  #   - ./state/openldap/init-scripts:/assets/custom-scripts/
  #   # post-backup scripts
  #   - ./state/openldap/post-backup-scripts:/assets/custom-backup-scripts/
  #   # certs
  #   - ./state/openldap/certs:/certs/
  #   # backup
  #   - ./state/openldap/backups:/data/backup

  #   # --- FusionDirectory Volumes ---
  #   # /www/fusiondirectory/html overrides
  #   - ./state/fusiondirectory/www-overrides:/assets/fusiondirectory
  #   # custom plugins
  #   - ./state/fusiondirectory/custom-plugins:/assets/plugins-custom/
  #   # custom schemas
  #   - ./state/fusiondirectory/custom-schemas:/assets/fusiondirectory-custom/
  #   # time things
  #   #- /etc/timezone:/etc/timezone:ro
  #   #- /etc/localtime:/etc/localtime:ro
  #   # ports:
  #   # # DNS
  #   # - "53:53/tcp"
  #   # - "53:53/udp"
  #   # # LDAP
  #   # - "389:389/tcp"
  #   # - "636:636/tcp"
  #   # # HTTP
  #   # - "443:443/tcp"
  #   # - "80:80/tcp"

