#SPDX-License-Identifier: MIT-0
---
# Ensure required packages are installed
- name: Install LDAP and PAM libraries
  ansible.builtin.package:
    name:
      - sssd
      - libpam-sss
      - libnss-sss
      - oddjob
      - oddjob-mkhomedir
      - ldap-utils
      - sssd-tools
      - libsss-sudo
    state: present

#- name: Configure NSS passwd to use SSS
#  ansible.builtin.lineinfile:
#    path: /etc/nsswitch.conf
#    regexp: '^passwd:'
#    line: 'passwd: files systemd sss'
#    backup: yes

#- name: Configure NSS group to use SSS
#  ansible.builtin.lineinfile:
#    path: /etc/nsswitch.conf
#    regexp: '^group:'
#    line: 'group: files systemd sss'
#    backup: yes

#- name: Configure NSS shadow to use SSS
#  ansible.builtin.lineinfile:
#    path: /etc/nsswitch.conf
#    regexp: '^shadow:'
#    line: 'shadow: files systemd sss'
#    backup: yes

#- name: Configure PAM to use LDAP
#  ansible.builtin.lineinfile:
#    path: /etc/pam.d/common-password
#    regexp: '^password.*sufficient.*pam_unix.so'
#    line: 'password    sufficient    pam_unix.so use_authtok md5 shadow'

# Configure LDAP client settings
- name: Configure /etc/sssd/sssd.conf
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: '0600'
  notify: restart sssd

# This is mostly for ldap-utils.
- name: Configure /etc/ldap/ldap.conf
  ansible.builtin.template:
    src: ldap.conf.j2
    dest: /etc/ldap/ldap.conf
    owner: root
    group: root
    mode: '0644'

- name: Update PAM config for sss
  ansible.builtin.command: pam-auth-update --enable sss
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: ansible_facts['os_family'] == 'Debian'

- name: Update PAM config for mkhomedir
  ansible.builtin.command: pam-auth-update --enable mkhomedir
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: ansible_facts['os_family'] == 'Debian'

# Enable and start services
- name: Ensure sssd service is running
  ansible.builtin.service:
    name: sssd
    state: restarted
    enabled: yes

