services:
  dnsmasq_svc:
    image: git.lab/lab/dnsmasq:stage
    container_name: dnsmasq_svc
    build:
      dockerfile_inline: |
        # Build depends on essential_pkgs_svc
        FROM alpine:latest
        RUN echo http://dockerhost:8000/alpine > /etc/apk/repositories
        RUN apk add -U --allow-untrusted dnsmasq
      extra_hosts: [ "dockerhost:host-gateway" ]
    restart: unless-stopped
    network_mode: host
    dns:
    - 9.9.9.9
    - 1.1.1.1
    dns_search: lab
    extra_hosts:
    - dockerhost:host-gateway
    - git.lab:192.168.1.5
    - words.lab:192.168.1.5
    - dns.lab:192.168.1.5
    - www.lab:192.168.1.5
    - tls.lab:192.168.1.5
    entrypoint: ["/usr/sbin/dnsmasq", "--no-daemon"]