---
# Port used by caddy-router-deployment
apiVersion: v1
kind: Service
metadata:
  name: words-service
  namespace: lab-words-ns
spec:
  selector:
    app: lab-words
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 1080
    targetPort: 80
  - name: port3012
    protocol: TCP
    port: 3012
    targetPort: 3012
