---
- name: Configure LDAP authentication
  hosts: all
  become: true
  roles:
   - role: root-cert-setup
   #vars:
   #     certificate_install_path: "/usr/local/share/ca-certificates"
   #     certificate_name: "lab-root.crt"
   - role: shares-setup
   - role: sss-setup
   #   vars:
   #     # Note: These are all unused at the moment.
   #     ldap_server: "ldap://server.lab.lan"
   #     ldap_base_dn: "dc=lab,dc=lan"
   #     ldap_bind_dn: "cn=admin,dc=lab,dc=lan"
   #     ldap_bind_password: "password"
   #     ldap_tls: false
        

