services:
  critical_pkg_svc:
    image: caddy:alpine
    volumes:
      - ${PWD}/data:/data
    working_dir: /data
    ports: [ "8000:80" ]
    entrypoint: caddy file-server --root /data --browse

  dnsmasq_svc:
    depends_on: [ critical_pkg_svc ]
    image: gods/dnsmasq_svc:latest
    build:
      context: data/context
      dockerfile_inline: |
        FROM alpine:latest
        RUN echo http://dockerhost:8000/alpine > /etc/apk/repositories
        RUN apk add -U --allow-untrusted dnsmasq
      extra_hosts: [ "dockerhost:host-gateway" ]
