apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace Override
#namespace: system-manual-ns
# Name Prefix Override
#namePrefix: dev-
# Name Suffix Override
#nameSuffix: -001

resources:
- manual-ns.yaml
- manual-deployment.yaml
- manual-service.yaml
# - systems-flux-secret.yaml
# - systems-flux-image-poll.yaml
# - systems-flux-git-deploy.yaml
# - systems-flux-notify.yaml
