services:
  critical_pkg_svc:
    image: caddy:alpine
    volumes:
      - /opt/state/critical_pkg_svc/data:/data
      #- ${PWD}/data:/data
    working_dir: /data
    ports: [ "8000:80" ]
    entrypoint: caddy file-server --root /data --browse