apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: git-db-statefulset
  namespace: lab-git-ns
spec:
  serviceName: "git-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: lab-git-db
  template:
    metadata:
      labels:
        app: lab-git-db
    spec:
      containers:
      - name: gitea_db
        image: git.lab/lab/gitea_db:stage
        env:
        - name: POSTGRES_DB
          valueFrom: { secretKeyRef: { name: git-db-secrets, key: POSTGRES_DB } }
        - name: POSTGRES_USER
          valueFrom: { secretKeyRef: { name: git-db-secrets, key: POSTGRES_USER } }
        - name: POSTGRES_PASSWORD
          valueFrom: { secretKeyRef: { name: git-db-secrets, key: POSTGRES_PASSWORD } }
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        hostPath: { path: /opt/state/lab-git/postgres }

