---
# Handled by ServiceLB (i.e. Klipper) in K3s
apiVersion: v1
kind: Service
metadata:
  name: git-ssh-service
  namespace: lab-git-ns
spec:
  selector:
    app: lab-git
  type: LoadBalancer
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
