##SPDX-License-Identifier: MIT-0
---

- name: Ensure NFS mount is present in /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "nfs.lab.lan:/exports/users /home/users nfs4 rw,soft,intr 0 0"
    state: present
    create: yes
    backup: yes
