#SPDX-License-Identifier: MIT-0
---
# tasks file for deploy-root-cert

- name: Install ca-certificates package libraries
  ansible.builtin.package:
    name:
      - ca-certificates
    state: present
  when: ansible_facts['os_family'] == 'Debian'


- name: Ensure the target certificate directory exists
  file:
    path: "{{ certificate_dest_dpath }}"
    state: directory
    mode: '0755'

- name: Deploy the root certificate
  copy:
    src: lab-root.crt
    dest: "{{ certificate_dest_dpath }}/{{ certificate_dest_fname }}"
    owner: root
    group: root
    mode: '0644'

- name: Update certificate store (Debian/Ubuntu)
  command: "update-ca-certificates"
  when: ansible_facts['os_family'] == 'Debian'

#- name: Update certificate store (RHEL/CentOS)
#  command: "update-ca-trust"
#  when: ansible_facts['os_family'] == 'RedHat'
