apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace Override
#namespace: namespace-ns
# Name Prefix Override
#namePrefix: dev-
# Name Suffix Override
#nameSuffix: -001

resources:
- git-ns.yaml
- git-db-secrets.yaml
- git-db-statefulset.yaml
- git-db-service.yaml
- git-deployment.yaml
- git-service.yaml
- git-ssh-service.yaml

