---
# Handled by ServiceLB (i.e. Klipper) in K3s
apiVersion: v1
kind: Service
metadata:
  name: dns-service
  namespace: lan-lab-dns-ns
spec:
  selector:
    app: lan-lab-dns
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53